### ISSUE TITLE
ComfyUI execution error: 'LTXVScheduler' object has no attribute 'get_sigmas'

### ISSUE THREAD

**Issue by madias123** [mcmonkeyprojects/SwarmUI#1176]
### Expected Behavior

Hello,
using LTXV Image To Video straight as in manual with ltx-video-2b-v0.9.5.safetensors, drops this error.

### Actual Behavior

using image to video, see screenshot

<img width="2538" height="718" alt="Image" src="https://github.com/user-attachments/assets/50ef8b45-6d8d-4668-8ba5-0983728811df" />

### Steps to Reproduce

nothing special, just use ltx als image to video

### Debug Logs

https://paste.denizenscript.com/View/137933

### Other

There is also a reference to this error here:
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/1129
But nothing to fix in my case.

**Comment by mcmonkey4eva** [comment]
- probably solved now
- ltxv is kinda a bad model
- weird af gen to be posting for technical support with man

**Comment by madias123** [comment]
nop, didn't fix, but: doesn't matter: ltxv is indeed obsolet today.
